FROM node:18 AS builder

WORKDIR /frontend

COPY package*.json ./

RUN npm install

COPY . .

ARG VITE_BASE_URL
ARG VITE_USER_BASE_URL
ARG VITE_CAPTAIN_BASE_URL
ARG VITE_GOMAPS_PRO_API_KEY
ARG RAZORPAY_KEY_ID
ARG RAZORPAY_KEY_SECRET

RUN VITE_BASE_URL=$VITE_BASE_URL \
    VITE_USER_BASE_URL=$VITE_USER_BASE_URL \
    VITE_CAPTAIN_BASE_URL=$VITE_CAPTAIN_BASE_URL \
    VITE_GOMAPS_PRO_API_KEY=$VITE_GOMAPS_PRO_API_KEY \
    RAZORPAY_KEY_ID=$RAZORPAY_KEY_ID \
    RAZORPAY_KEY_SECRET=$RAZORPAY_KEY_SECRET \
    npm run build

RUN npm run build

FROM nginx:alpine

COPY --from=builder /frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
